Editorial changes
lamps-wg/draft-composite-kem pull request #56
Opened 2024-08-06 00:35 UTC by ounsworth

2024-09-25 15:04 UTC, ounsworth commented
The security considerations need more work, especially the one about key reuse.

Another argument against key reuse is documented in https://github.com/lamps-wg/draft-composite-sigs/issues/49

2024-09-26 09:20 UTC, janklaussner requested changes
2 small issues, one question

2024-09-26 09:20 UTC, janklaussner commented on draft-ietf-lamps-pq-composite-kem.md
> +  I-D.draft-ietf-pquip-pqt-hybrid-terminology-03:
Its already -04

2024-09-26 09:20 UTC, janklaussner commented on draft-ietf-lamps-pq-composite-kem.md
> +In all cases above, the hash function used as a KDF produces a longer output than needed by the encryption algorithm, so the output should simply be truncated to the correct length -- ie use the left
Is there a reason why it says „should“ and not „shall“ or „must“? Proposal: 
[..] output shall be truncated […] by using the leftmost bits.

2024-09-26 09:20 UTC, janklaussner commented on draft-ietf-lamps-pq-composite-kem.md
> +With regard to the traditional algorithms, RSA or Elliptic CUrve, in order to achieve the public-key binding property the KEM combiner used to form the composite KEM, the combiner requires the tradit
Typo: „CUrve“

2024-09-27 14:51 UTC, ounsworth commented
Closes #72

2024-09-28 16:55 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-kem.md
> +ML-KEM always requires the public key in order to perform various steps of the Fujisaki-Okamoto decapsulation [FIPS203-ipd]. Additionally, in order to achaive the public-key binding property the KEM
typo "achaive".

2024-09-28 16:55 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-kem.md
> +When a `CompositePrivateKey` is conveyed inside a OneAsymmetricKey structure (version 1 of which is also known as PrivateKeyInfo) [RFC5958], then a situation arises where multiple `OneAsymmetricKey`s
We should think about this more. ML-KEM's FO requires the public key anyway, so the ML-KEM's private key needs to have it anyway, so we don't need to duplicate it at the composite layer. Same for RSA: the public key is a subset of the private key. We only really need to think about ECC (RFC 5915). Perhaps we need to treat ECC as a special case here?

Certainly, the "MUST" needs to be broken out into cases.

2024-09-28 16:55 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-kem.md
> +ML-KEM always requires the public key in order to perform various steps of the Fujisaki-Okamoto decapsulation [FIPS203-ipd]. Additionally, in order to achaive the public-key binding property the KEM
Done

2024-09-28 16:55 UTC, ounsworth commented on draft-ietf-lamps-pq-composite-kem.md
> +When a `CompositePrivateKey` is conveyed inside a OneAsymmetricKey structure (version 1 of which is also known as PrivateKeyInfo) [RFC5958], then a situation arises where multiple `OneAsymmetricKey`s
Done

2024-09-28 16:58 UTC, ounsworth commented
This PR has not been fully reviewed by the author's group, but I have been over it several times and I am merging it to close off all the related Issues.

2024-09-28 17:00 UTC, merged