Mikeo key reuse
lamps-wg/draft-composite-kem pull request #71
Opened 2024-09-26 19:23 UTC by ounsworth

2024-10-01 02:17 UTC, br-hale commented on draft-ietf-lamps-pq-composite-kem.md
> +When using single-algorithm cryptography, the best practice is to always generate fresh key material for each purpose, for example when renewing a certificate, or obtaining both a TLS and S/MIME cert
Suggested edit:

When using single-algorithm cryptography, the best practice is to always generate fresh keying material for each purpose, for example when renewing a certificate, or obtaining both a TLS and S/MIME certificate for the same device, however in practice key reuse in such scenarios is not always catastrophic to security and therefore often tolerated.

2024-10-01 02:57 UTC, br-hale commented on draft-ietf-lamps-pq-composite-kem.md
> +Within the broader context of PQ / Traditional hybrids, we need to consider new attack surfaces that arise due to the hybrid constructions and did not exist in single-algorithm contexts. One of these
Suggested edit:

"However there is still a risk of key reuse which relates to certificate revocation, as well as general key reuse security issues."

2024-10-15 19:02 UTC, janklaussner requested changes

2024-10-15 19:02 UTC, janklaussner commented on draft-ietf-lamps-pq-composite-kem.md
> +This document introduces a set of Key Encapsulation Mechanism (KEM) schemes that use pairs of cryptographic elements such as public keys and cipher texts to combine their security properties. These s
...eleven specific pairwise combinations...
count is currently nine, right?

2024-10-15 19:02 UTC, janklaussner commented on draft-ietf-lamps-pq-composite-kem.md
> +The notion of a second pre-image resistant KEM is defined in [X-Wing] being the property that it is computationally difficult to find two different ciphertexts `c != c'` that will decapsulate to the
[...]and therefore IND-CCA2 secure so, long as [...]
-> [...] secure, so long as [...]

2024-10-15 19:02 UTC, janklaussner commented on draft-ietf-lamps-pq-composite-kem.md
> +Traditionally, a public key or certificate contains a single cryptographic algorithm. If and when an algorithm becomes deprecated (for example, RSA-512, or SHA1), it is obvious that the public keys o
is this statement true? Afaik its more complicated in the real world. Is there an RFC describing this?

2024-10-17 20:47 UTC, merged